openapi: 3.0.0
info:
  title: Signup API
  version: '1.0.0'
  description: |
    Minimal API spec for Signup and Verification endpoints used in sample_data.

servers:
  - url: https://api.example.com/v1

paths:
  /signup:
    post:
      summary: Create a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: Created — verification email sent (if enabled)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: Bad request (validation failed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Duplicate email
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /verify:
    get:
      summary: Verify email using token
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Verification successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
        '400':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '410':
          description: Token expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    SignupRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        name:
          type: string
      example:
        email: new_user@example.com
        password: StrongPass#123
        name: "Jane Doe"

    SignupResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        verification_sent:
          type: boolean
      example:
        id: "user_1234"
        email: new_user@example.com
        verification_sent: true

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "EMAIL_EXISTS"
        message: "An account already exists for this email."

  securitySchemes: {}

tags:
  - name: signup
    description: Endpoints related to user signup and verification
